### ISSUE TITLE
JDK not found

### ISSUE THREAD

**Issue by nikgtasa** [BLCK-B/MusicReleaseTracker#5]
Windows 22H2, jdk 20, trying to set the jdk path to either the Java folder or jdk folders doesn't work and the program doesn't start. 
![image](https://github.com/BLCK-B/MusicReleaseTracker/assets/38408810/2e9ec286-34f5-4032-b6e8-248e2a6fa55a)
![image](https://github.com/BLCK-B/MusicReleaseTracker/assets/38408810/a0479ee2-6e45-4796-8e1b-e97f86c48c26)

**Comment by BLCK-B** [comment]
Hi, thanks for the issue. It works for me by clicking the jdk-20 so that it's selected. Basically the location of jdk-20 folder.

**Comment by nikgtasa** [comment]
Doesn't work for me. Maybe has something to do with Java folder location? I got it on a non-system drive in Program Files.

**Comment by BLCK-B** [comment]
That's the most likely issue. I did not test but assumed that this path selection would work for all cases, partitions and drives. If you can, I suggest trying a different drive.
On a side note, the JDK requirement will likely be dropped once I get to ditching OpenJFX in favour of a better UI framework.

**Comment by nikgtasa** [comment]
Different drive for your program or jdk?

**Comment by BLCK-B** [comment]
You can simply copy jdk-20 folder elsewhere. As for the installer, it creates a folder in appdata, which should not matter.

**Comment by BLCK-B** [comment]
How is it looking?

**Comment by nikgtasa** [comment]
![image](https://github.com/BLCK-B/MusicReleaseTracker/assets/38408810/3bbb3a40-54ed-481d-9d1e-4c81c3b8f658)
I put both of them on C drive, downloaded jdk20 in rar, unpacked, set the path and got the same error.

**Comment by BLCK-B** [comment]
I was able to replicate. The reason for this behaviour: in the installer code, the user-specified path is not actually applied as environment variable - it is virtually useless. The program works for most since during exe creation a generic path is specified, which is currently the only viable option.
The solution for you is to move the folder to C:\Program Files\Java\ and rename it accordingly (does not matter if it is a different version). The location must be  **C:\Program Files\Java\jdk-20**

I am aware that this is a silly solution. I will try tomorrow to get the installer code working as it should. In case of failure, I will at least put a disclaimer.. while the whole JDK situation is relevant. Thanks for the patience and please confirm whether it works this way.

**Comment by BLCK-B** [comment]
The installer was redone in NSIS. While I tried both automatic and manual JDK selection, I could not get it to work. Despite manually editing registries, the error persisted. The new installer has a check for the JDK folder, which points user to information on how to solve it. I'm now closing the issue to release a new version.
